workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 30
    instance_type: mac_mini
    environment:
      android_sdk:
        build_tools: "30.0.3"
    scripts:
      - name: Build Android APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/**/*.apk
